/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    events: Event;
    people: Person;
    testimonials: Testimonial;
    stats: Stat;
    heroes: Hero;
    media: Media;
    submissions: Submission;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    heroes: HeroesSelect<false> | HeroesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Articles shown on the Resources → Blog page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * The web address for this item. Leave blank to generate one.
   */
  slug: string;
  status: 'draft' | 'published';
  category: 'Leadership' | 'Global Experiences' | 'Professional Development' | 'Advocacy' | 'Wellness' | 'Student Life';
  /**
   * The short summary shown on the blog index card.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Falls back to a stock site photo if left empty.
   */
  featuredImage?: (number | null) | Media;
  publishedDate: string;
  author?: (number | null) | Person;
  /**
   * Show this post large at the top of the blog page.
   */
  featured?: boolean | null;
  /**
   * e.g. "6 min read". Calculated automatically if blank.
   */
  readTime?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines. Required.
   */
  alt: string;
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Founders, leadership, speakers and ambassadors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * The web address for this item. Leave blank to generate one.
   */
  slug: string;
  status: 'draft' | 'published';
  role: string;
  /**
   * Which pages this person appears on. A person can be in several.
   */
  groups: ('founder' | 'leadership' | 'speaker' | 'ambassador')[];
  photo?: (number | null) | Media;
  /**
   * Used on cards and grid listings.
   */
  shortBio?: string | null;
  /**
   * Full biography for this person's own page.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ambassadors only — the city they represent.
   */
  city?: string | null;
  speakingTopics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  website?: string | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every dated event on the site. Dates and prices here drive the Experiences pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * The web address for this item. Leave blank to generate one.
   */
  slug: string;
  status: 'draft' | 'published';
  type: 'conference' | 'wellness-retreat' | 'leadership-retreat' | 'global' | 'local' | 'meetup';
  startDate: string;
  /**
   * Leave blank for a single-day event.
   */
  endDate?: string | null;
  location: string;
  /**
   * Displayed as typed. Use "Free" where there is no cost.
   */
  price?: string | null;
  /**
   * One or two lines shown on event cards.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Where the Register button goes. Leave blank to use the built-in registration form.
   */
  registrationUrl?: string | null;
  registrationOpen?: boolean | null;
  /**
   * Show on the homepage Upcoming Events section.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Member and sponsor quotes used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The quote itself, without surrounding quote marks.
   */
  quote: string;
  author: string;
  /**
   * Credentials or job title.
   */
  role: string;
  status: 'draft' | 'published';
  placement: ('homepage' | 'sponsor-impact' | 'student-support' | 'scholarships')[];
  /**
   * Optional. With no photo the card shows the person's initials instead.
   */
  photo?: (number | null) | Media;
  /**
   * Confirm this person agreed to their name and quote being published.
   */
  consentGiven: boolean;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The big numbers shown on the homepage and Impact pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  value: string;
  label: string;
  /**
   * The icon shown above the number.
   */
  icon: 'Users' | 'BookOpen' | 'GraduationCap' | 'Globe' | 'HeartHandshake' | 'Stethoscope' | 'HandHeart';
  placement: ('homepage' | 'impact' | 'service' | 'community-online')[];
  status: 'draft' | 'published';
  /**
   * Internal only — never shown on the website. Record where this figure comes from.
   */
  sourceNote?: string | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The headline and background photo at the top of each page. Editing one here overrides what the page ships with.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroes".
 */
export interface Hero {
  id: number;
  /**
   * Friendly name shown in this list, e.g. "Ghana Experience".
   */
  pageName: string;
  /**
   * The page address this banner belongs to, e.g. "/experiences/ghana".
   */
  page: string;
  status: 'draft' | 'published';
  /**
   * The background photo. Leave empty to keep the photo the page already uses.
   */
  image?: (number | null) | Media;
  /**
   * The large headline. Leave empty to keep the current one.
   */
  heading?: string | null;
  /**
   * Optional trailing words shown in the brand accent colour.
   */
  highlight?: string | null;
  /**
   * The paragraph under the headline.
   */
  description?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything sent through the website's forms. Newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  formType:
    | 'contact'
    | 'newsletter'
    | 'membership'
    | 'conference'
    | 'ghana'
    | 'retreat'
    | 'scholarship'
    | 'speaker-booking'
    | 'volunteer'
    | 'partnership';
  /**
   * Auto-generated label for the list view.
   */
  summary?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  /**
   * Every remaining field exactly as the visitor submitted it.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Tick once actioned.
   */
  handled?: boolean | null;
  /**
   * Internal notes. Never public.
   */
  notes?: string | null;
  meta?: {
    sourceUrl?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Files submitted with applications. Visible to staff only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Which form this file arrived with.
   */
  formType?: string | null;
  /**
   * Which question it answers.
   */
  fieldName?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors manage content. Administrators also manage users.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'heroes';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  publishedDate?: T;
  author?: T;
  featured?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  type?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  price?: T;
  summary?: T;
  description?: T;
  image?: T;
  registrationUrl?: T;
  registrationOpen?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  role?: T;
  groups?: T;
  photo?: T;
  shortBio?: T;
  bio?: T;
  city?: T;
  speakingTopics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  email?: T;
  linkedin?: T;
  instagram?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  status?: T;
  placement?: T;
  photo?: T;
  consentGiven?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  icon?: T;
  placement?: T;
  status?: T;
  sourceNote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroes_select".
 */
export interface HeroesSelect<T extends boolean = true> {
  pageName?: T;
  page?: T;
  status?: T;
  image?: T;
  heading?: T;
  highlight?: T;
  description?: T;
  ctaLabel?: T;
  ctaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  formType?: T;
  summary?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  data?: T;
  handled?: T;
  notes?: T;
  meta?:
    | T
    | {
        sourceUrl?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  formType?: T;
  fieldName?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, social links and the notification address for form submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email: string;
  phone?: string | null;
  /**
   * Shown on the Contact page. Leave blank to hide.
   */
  address?: string | null;
  officeHours?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  twitter?: string | null;
  tiktok?: string | null;
  organisationName: string;
  tagline?: string | null;
  /**
   * Shown on the donation page. Donors ask for this at tax time.
   */
  ein?: string | null;
  nonprofitStatus?: string | null;
  /**
   * Where an alert is sent each time someone submits a form. Defaults to the contact email.
   */
  notificationEmail?: string | null;
  /**
   * Email us when a form is submitted.
   */
  notifyOnSubmission?: boolean | null;
  /**
   * Where the Donate button sends people (Givebutter, Donorbox, Stripe…). The button is disabled with a clear message until this is filled in.
   */
  donationUrl?: string | null;
  donationProvider?: ('none' | 'external') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  officeHours?: T;
  instagram?: T;
  facebook?: T;
  linkedin?: T;
  youtube?: T;
  twitter?: T;
  tiktok?: T;
  organisationName?: T;
  tagline?: T;
  ein?: T;
  nonprofitStatus?: T;
  notificationEmail?: T;
  notifyOnSubmission?: T;
  donationUrl?: T;
  donationProvider?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}